[package]
name = "coinbase_fix_md"
version = "0.1.0"
edition = "2021"

[dependencies]
forgefix = { git = "https://github.com/ForgeFinx/ForgeFIX" }
tokio = { version = "1.36.0", features = ["full"] }
anyhow = "1.0.75"
chrono = "0.4.31"
log = "0.4.20"
env_logger = "0.11.1"
