name: AutoDoc Issue Creator

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-ccxt-issue:
    if:
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'auto-docs-update')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Issue in CCXT Repository
        run: |
          chmod +x .github/scripts/create-ccxt-issue.sh
          .github/scripts/create-ccxt-issue.sh \
            "${{ github.event.pull_request.title }}" \
            "${{ github.event.pull_request.number }}" \
            "${{ github.event.pull_request.html_url }}" \
            "${{ github.event.pull_request.body }}" \
            "${{ github.event.pull_request.merged_by.login }}" \
            "${{ github.event.pull_request.merged_at }}" \
            "${{ github.repository_owner }}" \
            "${{ github.event.repository.name }}"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
