name: AutoDoc Issue Creator

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  create-ccrxt-issue:
    if:
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'auto-docs-update')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Issue in CCRXT Repository
        run: |
          chmod +x .github/scripts/create-ccrxt-issue.sh
          .github/scripts/create-ccrxt-issue.sh
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body }}
          MERGED_BY: ${{ github.event.pull_request.merged_by.login }}
          MERGED_AT: ${{ github.event.pull_request.merged_at }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
