name: Backpack Exchange Docs Update

on:
  schedule:
    # Run every Saturday at 23:00 UTC (Sunday morning)
    - cron: "0 23 * * 6"
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - "venues/backpack-exchange/**"

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        working-directory: venues/backpack-exchange

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git diff

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: venues/backpack-exchange/package-lock.json

      - name: Install AI PR summary tool dependencies
        run: |
          cd ../../tools/ai-pr-summary
          npm install

      - name: Install dependencies
        run: npm ci

      - name: Run Backpack Exchange scraper
        run: npm run extract:config

      - name: Check for changes
        id: git-check
        run: |
          cd ../..  # Move back to root directory for git operations
          # Explicitly add the docs/backpack directory to staging
          git add docs/backpack
          # Check if there are any changes
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Generate AI PR Summary
        if: steps.git-check.outputs.changes == 'true'
        id: ai-summary
        run: |
          cd ../..  # Move back to root directory for git operations
          # Generate AI summary using the AI PR summary tool (max diff length: 15000)
          SUMMARY=$(cd tools/ai-pr-summary && npm run generate-pr-summary ../../ 15000 2>/dev/null | sed -n '/---PR_SUMMARY_START---/,/---PR_SUMMARY_END---/p' | sed '1d;$d')
          # Escape the summary for GitHub Actions
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "docs: update Backpack Exchange API documentation"
          title: "Backpack Exchange API Documentation Update"
          branch: "backpack-exchange-docs-update"
          base: "main"
          delete-branch: true
          token: ${{ secrets.PAT_GITHUB }}
          body: ${{ steps.ai-summary.outputs.summary }}
          reviewers: "@rosssaunders"
          labels: "auto-docs-update"