name: Update Coinbase International Docs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 00:00 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install global dependencies
      run: npm install -g puppeteer

    - name: Install shared dependencies
      working-directory: venues/shared
      run: npm install

    - name: Install project dependencies
      working-directory: venues/coinbase-international
      run: npm install

    - name: Extract REST API docs
      working-directory: venues/coinbase-international
      run: npm run extract:rest
      continue-on-error: true

    - name: Extract FIX API docs
      working-directory: venues/coinbase-international
      run: npm run extract:fix
      continue-on-error: true

    - name: Extract WebSocket API docs
      working-directory: venues/coinbase-international
      run: npm run extract:websocket
      continue-on-error: true

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'docs: update Coinbase International API documentation'
        title: 'docs: update Coinbase International API documentation'
        body: |
          This PR updates the Coinbase International API documentation.
          
          Generated by the automated documentation update workflow.
        branch: update-coinbase-international-docs
        delete-branch: true